<?php
namespace App\Http\Controllers\Author;
use App\Http\Controllers\Controller;use App\Models\Category;use App\Models\License;use App\Models\Product;use App\Models\ProductImage;use App\Models\ProductLicense;use Illuminate\Http\Request;use Illuminate\Support\Facades\Auth;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class ProductController extends Controller{
 public function create(){
  $lifetime=(float) \App\Models\AuthorEarning::where('author_id',Auth::id())->sum('gross_amount');
  $tier=\App\Models\CommissionTier::where('is_active',true)->where('min_lifetime_sales','<=',$lifetime)->orderByDesc('min_lifetime_sales')->first();
  return response()->json([
    'categories'=>$this->pricingTree(),
    'licenses'=>License::where('status',1)->orderBy('sort_order')->orderBy('name')->get(),
    'pricing'=>['commission_percent'=>(float)($tier?->platform_fee_percent??0),'commission_tier'=>$tier?->name,'currency'=>'USD']
  ]);
 }
 public function store(Request $r){$v=$r->validate(['id'=>['nullable','prohibited'],'name'=>['required','string','max:255'],'category_id'=>['required','exists:categories,id'],'short_description'=>['required','string'],'description'=>['required','string'],'thumbnail'=>['required','string'],'preview_images'=>['required','array','min:1'],'preview_images.*'=>['string'],'file'=>['required','string'],'file_size'=>['nullable','integer','min:0'],'version'=>['required','string','max:50'],'demo_url'=>['nullable','url'],'status'=>['required','in:draft,pending'],'support_enabled'=>['nullable','boolean'],'licenses'=>['required','array','min:1'],'licenses.*'=>['required','numeric','min:0']]);$ids=array_keys($v['licenses']);$category=Category::findOrFail($v['category_id'])->pricingCategory();abort_unless($category->licenses()->where('status',true)->whereIn('licenses.id',$ids)->count()===count($ids),422,'One or more licenses are not enabled for this category.');$product=DB::transaction(function()use($v){$slug=$this->uniqueSlug($v['name']);$p=Product::create(['author_id'=>Auth::id(),'category_id'=>$v['category_id'],'name'=>$v['name'],'slug'=>$slug,'short_description'=>$v['short_description'],'description'=>$v['description'],'thumbnail'=>$v['thumbnail'],'file'=>$v['file'],'file_size'=>$v['file_size']??null,'version'=>$v['version'],'demo_url'=>$v['demo_url']??null,'status'=>$v['status'],'support_enabled'=>$v['support_enabled']??true]);$p->images()->createMany(collect($v['preview_images'])->map(fn($image)=>['image'=>$image])->all());$p->licenses()->createMany(collect($v['licenses'])->map(fn($price,$license)=>['license_id'=>$license,'price'=>$price])->values()->all());return $p;});return response()->json(['message'=>$product->status==='pending'?'Product submitted for review.':'Draft saved.','product'=>$product],201);}
 private function pricingTree(){ $categories=Category::where('status',1)->with('licenses')->orderBy('name')->get(); foreach($categories as $category){$category->setRelation('licenses',$category->pricingCategory()->licenses);} return $this->buildTree($categories);}
 private function uniqueSlug($name){$base=Str::slug($name);$slug=$base;$n=2;while(Product::withTrashed()->where('slug',$slug)->exists()){$slug=$base.'-'.$n++;}return $slug;}
 private function buildTree($categories,$parentId=null,$level=0){$out=[];foreach($categories->where('parent_id',$parentId) as $category){$category->display_name=str_repeat('— ',$level).$category->name;$out[]=$category;$out=array_merge($out,$this->buildTree($categories,$category->id,$level+1));}return $out;}
}