<?php
namespace App\Http\Controllers\Public;
use App\Http\Controllers\Controller; use App\Models\DownloadEntitlement; use App\Models\Order; use App\Models\PaymentEvent; use App\Services\MarketplaceSettings; use App\Services\OrderFulfillmentService; use App\Services\OrderService; use Illuminate\Http\Request; use Illuminate\Support\Facades\Http; use Illuminate\Support\Facades\Log; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException;
class CheckoutController extends Controller {
 public function methods(MarketplaceSettings $settings){return response()->json(['methods'=>$this->available($settings->group('payments'))]);}
 public function summary(Request $request,OrderService $orders,MarketplaceSettings $settings){$currency=strtoupper($settings->group('payments')['currency']??'USD');return response()->json(['summary'=>$orders->previewCart($request->user()->id,$currency,$settings)]);}
 public function start(Request $request,OrderService $orders,MarketplaceSettings $settings){
  $payment=$settings->group('payments');$provider=$request->validate(['provider'=>['required','in:stripe,razorpay,paypal']])['provider'];if(!in_array($provider,array_column($this->available($payment),'id'),true))throw ValidationException::withMessages(['payment'=>['The selected payment method is unavailable.']]);
  $order=$orders->createFromCart($request->user()->id,$provider,strtoupper($payment['currency']??'USD'),$settings);
  if($provider==='stripe'){$session=$this->stripe($order,$payment,$this->frontendUrl($request));$order->update(['provider_reference'=>$session['id']]);return response()->json(['order'=>$this->payload($order->fresh('items')),'provider'=>'stripe','checkout_url'=>$session['url']],201);}
  if($provider==='paypal'){$gateway=$this->paypalOrder($order,$payment);$order->update(['provider_reference'=>$gateway['id']]);return response()->json(['order'=>$this->payload($order->fresh('items')),'provider'=>'paypal','paypal'=>['client_id'=>$payment['paypal_client_id'],'order_id'=>$gateway['id'],'currency'=>$order->currency]],201);}
  $gateway=$this->razorpayOrder($order,$payment);$order->update(['provider_reference'=>$gateway['id']]);return response()->json(['order'=>$this->payload($order->fresh('items')),'provider'=>'razorpay','razorpay'=>['key'=>$payment['razorpay_key_id'],'order_id'=>$gateway['id'],'amount'=>$gateway['amount'],'currency'=>$gateway['currency'],'name'=>'MarketPlace','description'=>'Order '.$order->public_id]],201);
 }
 public function confirmStripe(Request $request,OrderFulfillmentService $fulfillment,MarketplaceSettings $settings){
  $data=$request->validate(['order_id'=>['required','uuid'],'session_id'=>['required','string','max:255']]);$payment=$settings->group('payments');
  $order=Order::where('public_id',$data['order_id'])->where('user_id',$request->user()->id)->where('provider','stripe')->firstOrFail();
  abort_unless(hash_equals((string)$order->provider_reference,$data['session_id']),422,'Payment session mismatch.');
  $response=Http::withBasicAuth($payment['stripe_secret_key']??'','')->get('https://api.stripe.com/v1/checkout/sessions/'.rawurlencode($data['session_id']));
  if($response->failed()){Log::warning('Stripe Checkout Session confirmation failed.',['status'=>$response->status(),'type'=>$response->json('error.type'),'code'=>$response->json('error.code')]);throw ValidationException::withMessages(['payment'=>['We could not verify this payment yet. Please refresh shortly.']]);}
  $session=$response->json();abort_unless(($session['payment_status']??null)==='paid'&&data_get($session,'metadata.order_public_id')===$order->public_id,422,'Payment has not been confirmed.');
  PaymentEvent::firstOrCreate(['provider'=>'stripe','event_id'=>'checkout_session_'.$data['session_id']],['order_id'=>$order->id,'event_type'=>'checkout.session.completed','payload'=>$session,'processed_at'=>now()]);
  $fulfillment->markPaid($order,$data['session_id']);return response()->json(['order'=>$this->payload($order->fresh('items.entitlements','items.purchaseVerifications'))]);
 }
 public function capturePayPal(Request $request,OrderFulfillmentService $fulfillment,MarketplaceSettings $settings){
  $data=$request->validate(['order_id'=>['required','uuid'],'paypal_order_id'=>['required','string']]);$payment=$settings->group('payments');$order=Order::where('public_id',$data['order_id'])->where('user_id',$request->user()->id)->where('provider','paypal')->firstOrFail();abort_unless(hash_equals((string)$order->provider_reference,$data['paypal_order_id']),422,'Payment order mismatch.');
  $response=Http::withToken($this->paypalToken($payment))->post($this->paypalBase($payment).'/v2/checkout/orders/'.$data['paypal_order_id'].'/capture');if($response->failed()||$response->json('status')!=='COMPLETED')throw ValidationException::withMessages(['payment'=>['PayPal could not confirm this payment.']]);PaymentEvent::firstOrCreate(['provider'=>'paypal','event_id'=>'capture_'.$data['paypal_order_id']],['order_id'=>$order->id,'event_type'=>'PAYMENT.CAPTURE.COMPLETED','payload'=>$response->json(),'processed_at'=>now()]);$fulfillment->markPaid($order,$data['paypal_order_id']);return response()->json(['order'=>$this->payload($order->fresh('items.entitlements','items.purchaseVerifications'))]);
 }
 public function verifyRazorpay(Request $request,OrderFulfillmentService $fulfillment,MarketplaceSettings $settings){
  $data=$request->validate(['order_id'=>['required','uuid'],'razorpay_payment_id'=>['required','string'],'razorpay_order_id'=>['required','string'],'razorpay_signature'=>['required','string']]);$secret=$settings->group('payments')['razorpay_key_secret']??null;abort_unless($secret,422,'Razorpay is not configured.');$order=Order::where('public_id',$data['order_id'])->where('user_id',$request->user()->id)->where('provider','razorpay')->firstOrFail();abort_unless(hash_equals((string)$order->provider_reference,$data['razorpay_order_id']),422,'Payment order mismatch.');abort_unless(hash_equals(hash_hmac('sha256',$data['razorpay_order_id'].'|'.$data['razorpay_payment_id'],$secret),$data['razorpay_signature']),422,'Invalid payment signature.');PaymentEvent::firstOrCreate(['provider'=>'razorpay','event_id'=>'client_'.$data['razorpay_payment_id']],['order_id'=>$order->id,'event_type'=>'payment.verified','payload'=>$data,'processed_at'=>now()]);$fulfillment->markPaid($order,$data['razorpay_order_id']);return response()->json(['order'=>$this->payload($order->fresh('items.entitlements','items.purchaseVerifications'))]);
 }
 public function show(Request $request,Order $order){abort_unless($order->user_id===$request->user()->id,403);return response()->json(['order'=>$this->payload($order->load(['items.entitlements','items.purchaseVerifications']))]);}
 public function purchases(Request $request){return response()->json(['orders'=>Order::where('user_id',$request->user()->id)->where('status','paid')->with(['items.entitlements','items.purchaseVerifications'])->latest('paid_at')->get()->map(fn($order)=>$this->payload($order))]);}
 public function download(Request $request,DownloadEntitlement $entitlement,MarketplaceSettings $settings){$entitlement->load('orderItem.product');abort_unless($entitlement->user_id===$request->user()->id,403);$product=$entitlement->orderItem?->product;abort_unless($product?->file,404,'Download file is unavailable.');$bucket=$settings->r2Bucket();abort_unless($bucket,422,'Cloud storage is not configured.');$command=$settings->r2Disk()->getClient()->getCommand('GetObject',['Bucket'=>$bucket,'Key'=>$product->file,'ResponseContentDisposition'=>'attachment; filename="'.Str::slug($product->name).'.zip"']);$url=(string)$settings->r2Disk()->getClient()->createPresignedRequest($command,'+10 minutes')->getUri();$entitlement->increment('download_count');$entitlement->update(['last_downloaded_at'=>now()]);return response()->json(['download_url'=>$url,'expires_in'=>600]);}
 public function stripeWebhook(Request $request,OrderFulfillmentService $fulfillment,MarketplaceSettings $settings){$payload=$request->getContent();$secret=$settings->group('payments')['stripe_webhook_secret']??null;abort_unless($secret&&$this->stripeSignature($payload,(string)$request->header('Stripe-Signature'),$secret),400,'Invalid Stripe signature.');$event=json_decode($payload,true,512,JSON_THROW_ON_ERROR);$eventId=$event['id']??null;abort_unless($eventId,400,'Missing event ID.');$record=PaymentEvent::firstOrCreate(['provider'=>'stripe','event_id'=>$eventId],['event_type'=>$event['type']??'unknown','payload'=>$event]);if($record->processed_at)return response()->json(['received'=>true]);$object=data_get($event,'data.object',[]);$order=Order::where('public_id',data_get($object,'metadata.order_public_id'))->first();if($order){$record->update(['order_id'=>$order->id]);if(($event['type']??'')==='checkout.session.completed'&&data_get($object,'payment_status')==='paid')$fulfillment->markPaid($order,data_get($object,'id'));}$record->update(['processed_at'=>now()]);return response()->json(['received'=>true]);}
 public function razorpayWebhook(Request $request,OrderFulfillmentService $fulfillment,MarketplaceSettings $settings){$payload=$request->getContent();$secret=$settings->group('payments')['razorpay_webhook_secret']??null;abort_unless($secret&&hash_equals(hash_hmac('sha256',$payload,$secret),(string)$request->header('X-Razorpay-Signature')),400,'Invalid Razorpay signature.');$event=json_decode($payload,true,512,JSON_THROW_ON_ERROR);$eventId=$request->header('X-Razorpay-Event-Id')??sha1($payload);$record=PaymentEvent::firstOrCreate(['provider'=>'razorpay','event_id'=>$eventId],['event_type'=>$event['event']??'unknown','payload'=>$event]);if($record->processed_at)return response()->json(['received'=>true]);$reference=data_get($event,'payload.payment.entity.order_id');$order=Order::where('provider','razorpay')->where('provider_reference',$reference)->first();if($order){$record->update(['order_id'=>$order->id]);if(($event['event']??'')==='payment.captured')$fulfillment->markPaid($order,$reference);}$record->update(['processed_at'=>now()]);return response()->json(['received'=>true]);}
 public function paypalWebhook(Request $request,OrderFulfillmentService $fulfillment,MarketplaceSettings $settings){$payment=$settings->group('payments');abort_unless(!empty($payment['paypal_webhook_id']),400,'PayPal webhook is not configured.');$event=$request->json()->all();$verify=Http::withToken($this->paypalToken($payment))->post($this->paypalBase($payment).'/v1/notifications/verify-webhook-signature',['auth_algo'=>$request->header('PAYPAL-AUTH-ALGO'),'cert_url'=>$request->header('PAYPAL-CERT-URL'),'transmission_id'=>$request->header('PAYPAL-TRANSMISSION-ID'),'transmission_sig'=>$request->header('PAYPAL-TRANSMISSION-SIG'),'transmission_time'=>$request->header('PAYPAL-TRANSMISSION-TIME'),'webhook_id'=>$payment['paypal_webhook_id'],'webhook_event'=>$event]);abort_unless($verify->successful()&&$verify->json('verification_status')==='SUCCESS',400,'Invalid PayPal signature.');$eventId=$event['id']??null;abort_unless($eventId,400,'Missing event ID.');$record=PaymentEvent::firstOrCreate(['provider'=>'paypal','event_id'=>$eventId],['event_type'=>$event['event_type']??'unknown','payload'=>$event]);if($record->processed_at)return response()->json(['received'=>true]);$reference=data_get($event,'resource.supplementary_data.related_ids.order_id');$order=Order::where('provider','paypal')->where('provider_reference',$reference)->first();if($order){$record->update(['order_id'=>$order->id]);if(($event['event_type']??'')==='PAYMENT.CAPTURE.COMPLETED')$fulfillment->markPaid($order,$reference);}$record->update(['processed_at'=>now()]);return response()->json(['received'=>true]);}
 private function available(array $p):array{$legacy=$p['provider']??null;$m=[];if(($p['stripe_enabled']??($legacy==='stripe'))&&!empty($p['stripe_secret_key']))$m[]=['id'=>'stripe','label'=>'Card, Apple Pay or Google Pay'];if(($p['razorpay_enabled']??($legacy==='razorpay'))&&!empty($p['razorpay_key_id'])&&!empty($p['razorpay_key_secret']))$m[]=['id'=>'razorpay','label'=>'Cards, UPI and local methods'];if(($p['paypal_enabled']??false)&&!empty($p['paypal_client_id'])&&!empty($p['paypal_client_secret']))$m[]=['id'=>'paypal','label'=>'PayPal wallet and eligible cards'];return $m;}
 private function frontendUrl(Request $r):string{$urls=array_values(array_filter(config('cors.allowed_origins',[]),fn($v)=>filter_var($v,FILTER_VALIDATE_URL)));$origin=rtrim((string)$r->header('Origin'),'/');if($origin&&in_array($origin,array_map(fn($v)=>rtrim($v,'/'),$urls),true))return $origin;if($urls)return rtrim($urls[0],'/');throw ValidationException::withMessages(['payment'=>['Frontend URL is missing from server CORS configuration.']]);}
 private function stripe(Order $o,array $p,string $base):array{$items=[];foreach($o->items as $i)$items[]=['price_data'=>['currency'=>strtolower($o->currency),'product_data'=>['name'=>$i->product_name.' - '.$i->license_name],'unit_amount'=>(int)round(((float)$i->unit_price+(float)$i->unit_buyer_fee)*100)],'quantity'=>$i->quantity];if((float)$o->handling_fee>0)$items[]=['price_data'=>['currency'=>strtolower($o->currency),'product_data'=>['name'=>'Handling fee'],'unit_amount'=>(int)round($o->handling_fee*100)],'quantity'=>1];$r=Http::withBasicAuth($p['stripe_secret_key'],'')->asForm()->post('https://api.stripe.com/v1/checkout/sessions',['mode'=>'payment','success_url'=>$base.'/checkout?order='.$o->public_id.'&session_id={CHECKOUT_SESSION_ID}','cancel_url'=>$base.'/checkout?cancelled=1','metadata'=>['order_public_id'=>$o->public_id],'line_items'=>$items]);if($r->failed()){Log::warning('Stripe Checkout Session creation failed.',['status'=>$r->status(),'type'=>$r->json('error.type'),'code'=>$r->json('error.code')]);throw ValidationException::withMessages(['payment'=>['Payment checkout could not be started. Check the active Stripe test/live credentials in Settings.']]);}return $r->json();}
 private function razorpayOrder(Order $o,array $p):array{$r=Http::withBasicAuth($p['razorpay_key_id'],$p['razorpay_key_secret'])->post('https://api.razorpay.com/v1/orders',['amount'=>(int)round($o->total*100),'currency'=>$o->currency,'receipt'=>$o->public_id]);if($r->failed())throw ValidationException::withMessages(['payment'=>['Payment checkout could not be started.']]);return $r->json();}
 private function paypalBase(array $p):string{return ($p['paypal_mode']??'sandbox')==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com';}
 private function paypalToken(array $p):string{$r=Http::withBasicAuth($p['paypal_client_id'],$p['paypal_client_secret'])->asForm()->post($this->paypalBase($p).'/v1/oauth2/token',['grant_type'=>'client_credentials']);if($r->failed()||!$r->json('access_token'))throw ValidationException::withMessages(['payment'=>['PayPal authorization failed.']]);return $r->json('access_token');}
 private function paypalOrder(Order $o,array $p):array{$r=Http::withToken($this->paypalToken($p))->withHeaders(['PayPal-Request-Id'=>$o->public_id])->post($this->paypalBase($p).'/v2/checkout/orders',['intent'=>'CAPTURE','purchase_units'=>[['reference_id'=>$o->public_id,'amount'=>['currency_code'=>$o->currency,'value'=>number_format((float)$o->total,2,'.','')]]]]);if($r->failed())throw ValidationException::withMessages(['payment'=>['Payment checkout could not be started.']]);return $r->json();}
 private function stripeSignature(string $payload,string $header,string $secret):bool{preg_match('/(?:^|,)t=(\\d+)/',$header,$t);preg_match_all('/(?:^|,)v1=([^,]+)/',$header,$s);if(empty($t[1])||abs(time()-(int)$t[1])>300)return false;$expected=hash_hmac('sha256',$t[1].'.'.$payload,$secret);foreach($s[1]??[] as $v)if(hash_equals($expected,$v))return true;return false;}
 private function payload(Order $o):array{return ['id'=>$o->public_id,'status'=>$o->status,'currency'=>$o->currency,'subtotal'=>$o->subtotal,'buyer_fee_total'=>$o->buyer_fee_total,'tax'=>$o->tax,'handling_fee'=>$o->handling_fee,'total'=>$o->total,'paid_at'=>$o->paid_at,'items'=>$o->items->map(function($i){$entitlements=$i->relationLoaded('entitlements')?$i->entitlements:collect();$verifications=$i->relationLoaded('purchaseVerifications')?$i->purchaseVerifications:collect();$codes=$verifications->keyBy('unit_number');return ['id'=>$i->id,'name'=>$i->product_name,'license'=>$i->license_name,'quantity'=>$i->quantity,'unit_price'=>$i->unit_price,'unit_buyer_fee'=>$i->unit_buyer_fee,'buyer_fee_total'=>$i->buyer_fee_total,'total'=>$i->total,'purchases'=>$entitlements->map(fn($entitlement)=>['unit_number'=>$entitlement->unit_number,'entitlement_id'=>$entitlement->id,'purchase_code'=>$codes->get($entitlement->unit_number)?->purchaseCode(),'support_until'=>$codes->get($entitlement->unit_number)?->support_until])];})];}
}