<?php
namespace App\Http\Controllers\Public;
use App\Http\Controllers\Controller;use App\Models\PurchaseVerification;use App\Models\SupportTicket;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
class SupportTicketController extends Controller {
 public function index(Request $request){$user=$request->user();$query=SupportTicket::with(['product:id,name,slug','customer:id,name','author:id,name'])->withCount('messages')->latest('last_replied_at');if($user->role==='author')$query->where('author_id',$user->id);else $query->where('customer_id',$user->id);return response()->json(['tickets'=>$query->get()]);}
 public function store(Request $request){$data=$request->validate(['purchase_code'=>['required','string','max:100'],'subject'=>['required','string','max:180'],'message'=>['required','string','max:5000']]);$code=strtoupper(trim($data['purchase_code']));$verification=PurchaseVerification::where('code_hash',hash('sha256',$code))->with('orderItem.product','orderItem.order')->first();$item=$verification?->orderItem;$product=$item?->product;if(!$verification||$item?->order?->user_id!==$request->user()->id||!$product)throw ValidationException::withMessages(['purchase_code'=>['Enter a valid purchase code from your account.']]);if(!$verification->support_until||!$verification->support_until->isFuture())throw ValidationException::withMessages(['purchase_code'=>['This purchase does not have active author support.']]);$ticket=DB::transaction(function()use($data,$verification,$item,$product,$request){$ticket=SupportTicket::create(['purchase_verification_id'=>$verification->id,'product_id'=>$product->id,'customer_id'=>$request->user()->id,'author_id'=>$product->author_id,'subject'=>$data['subject'],'status'=>'open','last_replied_at'=>now()]);$ticket->messages()->create(['user_id'=>$request->user()->id,'body'=>$data['message']]);return $ticket;});return response()->json(['message'=>'Support request sent.','ticket'=>$this->detail($ticket)],201);}
 public function show(Request $request,SupportTicket $ticket){$this->authorizeTicket($request,$ticket);return response()->json(['ticket'=>$this->detail($ticket)]);}
 public function message(Request $request,SupportTicket $ticket){$this->authorizeTicket($request,$ticket);$data=$request->validate(['message'=>['required','string','max:5000']]);if($ticket->status==='closed')throw ValidationException::withMessages(['message'=>['This support request is closed.']]);$ticket->messages()->create(['user_id'=>$request->user()->id,'body'=>$data['message']]);$ticket->update(['status'=>$ticket->customer_id===$request->user()->id?'open':'answered','last_replied_at'=>now()]);return response()->json(['message'=>'Reply sent.','ticket'=>$this->detail($ticket)]);}
 public function close(Request $request,SupportTicket $ticket){$this->authorizeTicket($request,$ticket);$ticket->update(['status'=>'closed']);return response()->json(['ticket'=>$this->detail($ticket)]);}
 private function authorizeTicket(Request $request,SupportTicket $ticket):void{abort_unless(in_array($request->user()->id,[$ticket->customer_id,$ticket->author_id],true),403);}
 private function detail(SupportTicket $ticket):array{$ticket->load(['product:id,name,slug','customer:id,name','author:id,name','messages.user:id,name']);return ['id'=>$ticket->id,'subject'=>$ticket->subject,'status'=>$ticket->status,'last_replied_at'=>$ticket->last_replied_at,'created_at'=>$ticket->created_at,'product'=>$ticket->product,'customer'=>$ticket->customer,'author'=>$ticket->author,'messages'=>$ticket->messages->map(fn($message)=>['id'=>$message->id,'body'=>$message->body,'created_at'=>$message->created_at,'user'=>$message->user])];}
}